### PR TITLE
Fix #13: Remove active vote state on logout.

### LINKED ISSUE #13: Active vote button state isn't cleared on logout

### PR DESCRIPTION
**Pull request by simoneduca**
Also prevent voting when not logged in.

### CODE REVIEW

**Comment by simoneduca** [comment]
@rogerhutchings should be straightforward.

**Comment by rogerhutchings** [comment]
fine, but i would add the `disabled` attribute to buttons as well when logged out

**Comment by simoneduca** [comment]
@rogerhutchings should be good now.

**Comment by rogerhutchings** [comment]
Looks like this has introduced a weird bug - I can now vote any number of times on the same issue. This is only increasing the vote count, however, not the votes logged under my uid

**Comment by rogerhutchings** [comment]
Rebased and merged

**Pull request merged**
